#Github Actions workflow used to build the ionic app static resources and deploy to Azure blobstorage
name: Build Static App and Deploy to Azure Blobstorage
on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Install npm packages & Build
        run: |
          cd $GITHUB_WORKSPACE/
          npm install
          npm run build

      - name: Publish app to Azure blob storage
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
